#!/bin/bash
#
# Skill Memory 安装脚本
# 支持全程回车完成安装
#

set -e

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# 配置
SKILL_ROOT="${HOME}/.skill-memory"
QODER_CONFIG="${HOME}/.qoder/settings.json"
GITHUB_RAW_URL="https://raw.githubusercontent.com/jiazhizhuo/skill-memory/main"

echo_step() {
    echo -e "\n${BLUE}==>${NC} $1"
}

echo_success() {
    echo -e "${GREEN}✓${NC} $1"
}

echo_warn() {
    echo -e "${YELLOW}⚠${NC} $1"
}

echo_error() {
    echo -e "${RED}✗${NC} $1"
}

# 检查命令是否存在
check_command() {
    if ! command -v $1 &> /dev/null; then
        echo_error "$1 not found. Please install $1 first."
        return 1
    fi
    return 0
}

# 主安装流程
main() {
    echo -e "\n${BLUE}======================================${NC}"
    echo -e "${BLUE}  Skill Memory 安装向导${NC}"
    echo -e "${BLUE}======================================${NC}\n"

    # 1. 检查依赖
    echo_step "检查系统依赖..."

    if check_command "python3"; then
        PYTHON_CMD="python3"
    elif check_command "python"; then
        PYTHON_CMD="python"
    else
        echo_error "Python not found"
        exit 1
    fi

    PYTHON_VERSION=$($PYTHON_CMD --version 2>&1 | grep -oP '\d+\.\d+' | head -1)
    if (( $(echo "$PYTHON_VERSION < 3.10" | bc -l) 2>/dev/null || echo "0" )); then
        echo_warn "Python 3.10+ recommended, found $PYTHON_VERSION"
    fi
    echo_success "Python: $($PYTHON_CMD --version)"

    # 检查 Docker
    if command -v docker &> /dev/null; then
        echo_success "Docker found"
        HAS_DOCKER=true
    else
        echo_warn "Docker not found (optional for Qdrant)"
        HAS_DOCKER=false
    fi

    # 2. 创建目录
    echo_step "创建目录结构..."
    mkdir -p "${SKILL_ROOT}"/{src,hooks,scripts,tests,memory,knowledge}
    echo_success "目录创建完成: ${SKILL_ROOT}"

    # 3. 检查源文件
    echo_step "检查核心文件..."

    REQUIRED_FILES=(
        "src/config.py"
        "src/mem0_client.py"
        "src/transcript_parser.py"
        "src/memory_manager.py"
        "src/cli.py"
        "hooks/mem0_memory_hook.py"
    )

    MISSING_FILES=()
    for file in "${REQUIRED_FILES[@]}"; do
        if [ ! -f "${SKILL_ROOT}/${file}" ]; then
            MISSING_FILES+=("$file")
        fi
    done

    if [ ${#MISSING_FILES[@]} -gt 0 ]; then
        echo_warn "缺少以下文件，正在创建..."
        for file in "${MISSING_FILES[@]}"; do
            echo "  - $file"
            # 文件应该已由 Qoder 创建，这里仅提示
        done
    else
        echo_success "核心文件完整"
    fi

    # 4. 安装 Python 依赖
    echo_step "安装 Python 依赖..."

    # 检查 pip
    if ! $PYTHON_CMD -m pip --version &> /dev/null; then
        echo_warn "pip not found, trying pip3..."
        if ! command -v pip3 &> /dev/null; then
            echo_error "pip not found. Please install pip first."
            exit 1
        fi
    fi

    # 安装必要依赖
    $PYTHON_CMD -m pip install --user python-dotenv requests --quiet 2>/dev/null || true

    # 可选：安装 mem0
    echo -e "\n是否安装 mem0 (用于高级向量存储)? [Y/n]"
    read -r -t 10 response || response="y"
    response=${response:-y}

    if [[ "$response" =~ ^[Yy]$ ]]; then
        echo "安装 mem0..."
        $PYTHON_CMD -m pip install --user mem0 --quiet 2>/dev/null || echo_warn "mem0 安装失败，将使用降级模式"
    fi

    # 5. 启动 Qdrant (可选)
    if [ "$HAS_DOCKER" = true ]; then
        echo -e "\n是否启动 Qdrant 向量数据库? [Y/n]"
        read -r -t 10 response || response="y"
        response=${response:-y}

        if [[ "$response" =~ ^[Yy]$ ]]; then
            echo_step "启动 Qdrant..."

            # 检查是否已运行
            if docker ps | grep -q qdrant; then
                echo_success "Qdrant 已在运行"
            else
                docker run -d \
                    --name qdrant \
                    -p 6333:6333 \
                    -p 6334:6334 \
                    -v "${SKILL_ROOT}/memory/qdrant_storage:/qdrant/storage" \
                    qdrant/qdrant 2>/dev/null || echo_warn "Qdrant 启动失败"

                if curl -s http://localhost:6333/health &>/dev/null; then
                    echo_success "Qdrant 启动成功"
                else
                    echo_warn "Qdrant 可能未正常启动"
                fi
            fi
        fi
    else
        echo_warn "跳过 Qdrant 安装 (需要 Docker)"
    fi

    # 6. 配置环境变量
    echo_step "配置环境变量..."

    ENV_FILE="${SKILL_ROOT}/.env"

    if [ ! -f "$ENV_FILE" ]; then
        cat > "$ENV_FILE" << EOF
# Skill Memory Configuration
# Generated by install.sh

# Qdrant Configuration
SKILL_MEMORY_QDRANT_HOST=localhost
SKILL_MEMORY_QDRANT_PORT=6333
SKILL_MEMORY_QDRANT_COLLECTION=qoder_memory

# LLM/Embedding Provider
SKILL_MEMORY_LLM_PROVIDER=openai
SKILL_MEMORY_EMBEDDING_PROVIDER=openai
SKILL_MEMORY_LLM_MODEL=gpt-4o-mini
SKILL_MEMORY_EMBEDDING_MODEL=text-embedding-3-small

# API Key (optional, can also use environment variables)
# SKILL_MEMORY_API_KEY=your_key_here

# Search Parameters
SKILL_MEMORY_VECTOR_WEIGHT=0.7
SKILL_MEMORY_KEYWORD_WEIGHT=0.3
SKILL_MEMORY_DEFAULT_TOP_K=5
SKILL_MEMORY_PROMOTION_THRESHOLD=0.8
EOF
        echo_success "配置文件已创建: ${ENV_FILE}"
        echo_warn "请编辑 ${ENV_FILE} 填入您的 API Key"
    else
        echo_success "配置文件已存在: ${ENV_FILE}"
    fi

    # 7. 配置 Qoder Hooks
    echo_step "配置 Qoder Hooks..."

    QODER_CONFIG_DIR=$(dirname "$QODER_CONFIG")
    mkdir -p "$QODER_CONFIG_DIR"

    if [ -f "$QODER_CONFIG" ]; then
        # 备份原配置
        cp "$QODER_CONFIG" "${QODER_CONFIG}.backup.$(date +%Y%m%d%H%M%S)"
        echo_success "已备份原配置"

        # 添加 hooks 配置
        if grep -q '"hooks"' "$QODER_CONFIG"; then
            echo_warn "hooks 配置已存在，跳过"
        else
            # 使用 jq 添加 hooks (如果可用)
            if command -v jq &> /dev/null; then
                jq '.hooks.Stop = [{"hooks": [{"type": "command", "command": "'"${SKILL_ROOT}/hooks/mem0_memory_hook.py"'"}]}]' \
                    "$QODER_CONFIG" > "${QODER_CONFIG}.tmp" && \
                    mv "${QODER_CONFIG}.tmp" "$QODER_CONFIG"
                echo_success "Qoder Hooks 配置已添加"
            else
                echo_warn "jq 未安装，请在 ${QODER_CONFIG} 手动添加 hooks 配置"
            fi
        fi
    else
        # 创建新配置
        cat > "$QODER_CONFIG" << EOF
{
  "hooks": {
    "Stop": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "${SKILL_ROOT}/hooks/mem0_memory_hook.py"
          }
        ]
      }
    ]
  }
}
EOF
        echo_success "Qoder 配置已创建"
    fi

    # 8. 创建 CLI 软链接
    echo_step "创建 CLI 命令..."

    BIN_DIR="${HOME}/.local/bin"
    mkdir -p "$BIN_DIR"

    if [ -f "${SKILL_ROOT}/src/cli.py" ]; then
        ln -sf "${SKILL_ROOT}/src/cli.py" "${BIN_DIR}/memory"
        chmod +x "${BIN_DIR}/memory"

        if [ -d "$BIN_DIR" ] && [[ ":$PATH:" == *":$BIN_DIR:"* ]]; then
            echo_success "CLI 命令已安装: memory"
        else
            echo_warn "请将 ${BIN_DIR} 添加到 PATH"
            echo "  在 ~/.bashrc 或 ~/.zshrc 中添加:"
            echo "  export PATH=\"\$HOME/.local/bin:\$PATH\""
        fi
    fi

    # 9. 验证安装
    echo_step "验证安装..."

    if $PYTHON_CMD -c "from src.config import load_config; print('Config OK')" 2>/dev/null; then
        echo_success "Python 模块导入成功"
    else
        echo_warn "Python 模块导入失败，请检查 PYTHONPATH"
    fi

    if curl -s http://localhost:6333/health &>/dev/null; then
        echo_success "Qdrant 服务正常"
    else
        echo_warn "Qdrant 未运行，可选功能"
    fi

    # 完成
    echo -e "\n${GREEN}======================================${NC}"
    echo -e "${GREEN}  安装完成!${NC}"
    echo -e "${GREEN}======================================${NC}\n"

    echo "使用说明:"
    echo "  1. 编辑配置文件: ${ENV_FILE}"
    echo "  2. 添加 API Key"
    echo "  3. 使用 memory 命令:"
    echo "     memory add '用户偏好深色主题'"
    echo "     memory search '代码风格'"
    echo "     memory import --file <transcript.jsonl>"
    echo "     memory stats"
    echo -e "\n  ${BLUE}开始使用 AI 记忆系统吧!${NC}\n"
}

# 运行
main "$@"
#!/bin/bash
#
# Skill Memory 安装脚本
# 支持全程回车完成安装
#

set -e

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# 配置
SKILL_ROOT="${HOME}/.skill-memory"
QODER_CONFIG="${HOME}/.qoder/settings.json"
GITHUB_RAW_URL="https://raw.githubusercontent.com/jiazhizhuo/skill-memory/main"

echo_step() {
    echo -e "\n${BLUE}==>${NC} $1"
}

echo_success() {
    echo -e "${GREEN}✓${NC} $1"
}

echo_warn() {
    echo -e "${YELLOW}⚠${NC} $1"
}

echo_error() {
    echo -e "${RED}✗${NC} $1"
}

# 检查命令是否存在
check_command() {
    if ! command -v $1 &> /dev/null; then
        echo_error "$1 not found. Please install $1 first."
        return 1
    fi
    return 0
}

# 主安装流程
main() {
    echo -e "\n${BLUE}======================================${NC}"
    echo -e "${BLUE}  Skill Memory 安装向导${NC}"
    echo -e "${BLUE}======================================${NC}\n"

    # 1. 检查依赖
    echo_step "检查系统依赖..."

    if check_command "python3"; then
        PYTHON_CMD="python3"
    elif check_command "python"; then
        PYTHON_CMD="python"
    else
        echo_error "Python not found"
        exit 1
    fi

    PYTHON_VERSION=$($PYTHON_CMD --version 2>&1 | grep -oP '\d+\.\d+' | head -1)
    if (( $(echo "$PYTHON_VERSION < 3.10" | bc -l) 2>/dev/null || echo "0" )); then
        echo_warn "Python 3.10+ recommended, found $PYTHON_VERSION"
    fi
    echo_success "Python: $($PYTHON_CMD --version)"

    # 检查 Docker
    if command -v docker &> /dev/null; then
        echo_success "Docker found"
        HAS_DOCKER=true
    else
        echo_warn "Docker not found (optional for Qdrant)"
        HAS_DOCKER=false
    fi

    # 2. 创建目录
    echo_step "创建目录结构..."
    mkdir -p "${SKILL_ROOT}"/{src,hooks,scripts,tests,memory,knowledge}
    echo_success "目录创建完成: ${SKILL_ROOT}"

    # 3. 检查源文件
    echo_step "检查核心文件..."

    REQUIRED_FILES=(
        "src/config.py"
        "src/mem0_client.py"
        "src/transcript_parser.py"
        "src/memory_manager.py"
        "src/cli.py"
        "hooks/mem0_memory_hook.py"
    )

    MISSING_FILES=()
    for file in "${REQUIRED_FILES[@]}"; do
        if [ ! -f "${SKILL_ROOT}/${file}" ]; then
            MISSING_FILES+=("$file")
        fi
    done

    if [ ${#MISSING_FILES[@]} -gt 0 ]; then
        echo_warn "缺少以下文件，正在创建..."
        for file in "${MISSING_FILES[@]}"; do
            echo "  - $file"
            # 文件应该已由 Qoder 创建，这里仅提示
        done
    else
        echo_success "核心文件完整"
    fi

    # 4. 安装 Python 依赖
    echo_step "安装 Python 依赖..."

    # 检查 pip
    if ! $PYTHON_CMD -m pip --version &> /dev/null; then
        echo_warn "pip not found, trying pip3..."
        if ! command -v pip3 &> /dev/null; then
            echo_error "pip not found. Please install pip first."
            exit 1
        fi
    fi

    # 安装必要依赖
    $PYTHON_CMD -m pip install --user python-dotenv requests --quiet 2>/dev/null || true

    # 可选：安装 mem0
    echo -e "\n是否安装 mem0 (用于高级向量存储)? [Y/n]"
    read -r -t 10 response || response="y"
    response=${response:-y}

    if [[ "$response" =~ ^[Yy]$ ]]; then
        echo "安装 mem0..."
        $PYTHON_CMD -m pip install --user mem0 --quiet 2>/dev/null || echo_warn "mem0 安装失败，将使用降级模式"
    fi

    # 5. 启动 Qdrant (可选)
    if [ "$HAS_DOCKER" = true ]; then
        echo -e "\n是否启动 Qdrant 向量数据库? [Y/n]"
        read -r -t 10 response || response="y"
        response=${response:-y}

        if [[ "$response" =~ ^[Yy]$ ]]; then
            echo_step "启动 Qdrant..."

            # 检查是否已运行
            if docker ps | grep -q qdrant; then
                echo_success "Qdrant 已在运行"
            else
                docker run -d \
                    --name qdrant \
                    -p 6333:6333 \
                    -p 6334:6334 \
                    -v "${SKILL_ROOT}/memory/qdrant_storage:/qdrant/storage" \
                    qdrant/qdrant 2>/dev/null || echo_warn "Qdrant 启动失败"

                if curl -s http://localhost:6333/health &>/dev/null; then
                    echo_success "Qdrant 启动成功"
                else
                    echo_warn "Qdrant 可能未正常启动"
                fi
            fi
        fi
    else
        echo_warn "跳过 Qdrant 安装 (需要 Docker)"
    fi

    # 6. 配置环境变量
    echo_step "配置环境变量..."

    ENV_FILE="${SKILL_ROOT}/.env"

    if [ ! -f "$ENV_FILE" ]; then
        cat > "$ENV_FILE" << EOF
# Skill Memory Configuration
# Generated by install.sh

# Qdrant Configuration
SKILL_MEMORY_QDRANT_HOST=localhost
SKILL_MEMORY_QDRANT_PORT=6333
SKILL_MEMORY_QDRANT_COLLECTION=qoder_memory

# LLM/Embedding Provider
SKILL_MEMORY_LLM_PROVIDER=openai
SKILL_MEMORY_EMBEDDING_PROVIDER=openai
SKILL_MEMORY_LLM_MODEL=gpt-4o-mini
SKILL_MEMORY_EMBEDDING_MODEL=text-embedding-3-small

# API Key (optional, can also use environment variables)
# SKILL_MEMORY_API_KEY=your_key_here

# Search Parameters
SKILL_MEMORY_VECTOR_WEIGHT=0.7
SKILL_MEMORY_KEYWORD_WEIGHT=0.3
SKILL_MEMORY_DEFAULT_TOP_K=5
SKILL_MEMORY_PROMOTION_THRESHOLD=0.8
EOF
        echo_success "配置文件已创建: ${ENV_FILE}"
        echo_warn "请编辑 ${ENV_FILE} 填入您的 API Key"
    else
        echo_success "配置文件已存在: ${ENV_FILE}"
    fi

    # 7. 配置 Qoder Hooks
    echo_step "配置 Qoder Hooks..."

    QODER_CONFIG_DIR=$(dirname "$QODER_CONFIG")
    mkdir -p "$QODER_CONFIG_DIR"

    if [ -f "$QODER_CONFIG" ]; then
        # 备份原配置
        cp "$QODER_CONFIG" "${QODER_CONFIG}.backup.$(date +%Y%m%d%H%M%S)"
        echo_success "已备份原配置"

        # 添加 hooks 配置
        if grep -q '"hooks"' "$QODER_CONFIG"; then
            echo_warn "hooks 配置已存在，跳过"
        else
            # 使用 jq 添加 hooks (如果可用)
            if command -v jq &> /dev/null; then
                jq '.hooks.Stop = [{"hooks": [{"type": "command", "command": "'"${SKILL_ROOT}/hooks/mem0_memory_hook.py"'"}]}]' \
                    "$QODER_CONFIG" > "${QODER_CONFIG}.tmp" && \
                    mv "${QODER_CONFIG}.tmp" "$QODER_CONFIG"
                echo_success "Qoder Hooks 配置已添加"
            else
                echo_warn "jq 未安装，请在 ${QODER_CONFIG} 手动添加 hooks 配置"
            fi
        fi
    else
        # 创建新配置
        cat > "$QODER_CONFIG" << EOF
{
  "hooks": {
    "Stop": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "${SKILL_ROOT}/hooks/mem0_memory_hook.py"
          }
        ]
      }
    ]
  }
}
EOF
        echo_success "Qoder 配置已创建"
    fi

    # 8. 创建 CLI 软链接
    echo_step "创建 CLI 命令..."

    BIN_DIR="${HOME}/.local/bin"
    mkdir -p "$BIN_DIR"

    if [ -f "${SKILL_ROOT}/src/cli.py" ]; then
        ln -sf "${SKILL_ROOT}/src/cli.py" "${BIN_DIR}/memory"
        chmod +x "${BIN_DIR}/memory"

        if [ -d "$BIN_DIR" ] && [[ ":$PATH:" == *":$BIN_DIR:"* ]]; then
            echo_success "CLI 命令已安装: memory"
        else
            echo_warn "请将 ${BIN_DIR} 添加到 PATH"
            echo "  在 ~/.bashrc 或 ~/.zshrc 中添加:"
            echo "  export PATH=\"\$HOME/.local/bin:\$PATH\""
        fi
    fi

    # 9. 验证安装
    echo_step "验证安装..."

    if $PYTHON_CMD -c "from src.config import load_config; print('Config OK')" 2>/dev/null; then
        echo_success "Python 模块导入成功"
    else
        echo_warn "Python 模块导入失败，请检查 PYTHONPATH"
    fi

    if curl -s http://localhost:6333/health &>/dev/null; then
        echo_success "Qdrant 服务正常"
    else
        echo_warn "Qdrant 未运行，可选功能"
    fi

    # 完成
    echo -e "\n${GREEN}======================================${NC}"
    echo -e "${GREEN}  安装完成!${NC}"
    echo -e "${GREEN}======================================${NC}\n"

    echo "使用说明:"
    echo "  1. 编辑配置文件: ${ENV_FILE}"
    echo "  2. 添加 API Key"
    echo "  3. 使用 memory 命令:"
    echo "     memory add '用户偏好深色主题'"
    echo "     memory search '代码风格'"
    echo "     memory import --file <transcript.jsonl>"
    echo "     memory stats"
    echo -e "\n  ${BLUE}开始使用 AI 记忆系统吧!${NC}\n"
}

# 运行
main "$@"
#!/bin/bash
#
# Skill Memory 安装脚本
# 支持全程回车完成安装
#

set -e

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# 配置
SKILL_ROOT="${HOME}/.skill-memory"
QODER_CONFIG="${HOME}/.qoder/settings.json"
GITHUB_RAW_URL="https://raw.githubusercontent.com/jiazhizhuo/skill-memory/main"

echo_step() {
    echo -e "\n${BLUE}==>${NC} $1"
}

echo_success() {
    echo -e "${GREEN}✓${NC} $1"
}

echo_warn() {
    echo -e "${YELLOW}⚠${NC} $1"
}

echo_error() {
    echo -e "${RED}✗${NC} $1"
}

# 检查命令是否存在
check_command() {
    if ! command -v $1 &> /dev/null; then
        echo_error "$1 not found. Please install $1 first."
        return 1
    fi
    return 0
}

# 主安装流程
main() {
    echo -e "\n${BLUE}======================================${NC}"
    echo -e "${BLUE}  Skill Memory 安装向导${NC}"
    echo -e "${BLUE}======================================${NC}\n"

    # 1. 检查依赖
    echo_step "检查系统依赖..."

    if check_command "python3"; then
        PYTHON_CMD="python3"
    elif check_command "python"; then
        PYTHON_CMD="python"
    else
        echo_error "Python not found"
        exit 1
    fi

    PYTHON_VERSION=$($PYTHON_CMD --version 2>&1 | grep -oP '\d+\.\d+' | head -1)
    if (( $(echo "$PYTHON_VERSION < 3.10" | bc -l) 2>/dev/null || echo "0" )); then
        echo_warn "Python 3.10+ recommended, found $PYTHON_VERSION"
    fi
    echo_success "Python: $($PYTHON_CMD --version)"

    # 检查 Docker
    if command -v docker &> /dev/null; then
        echo_success "Docker found"
        HAS_DOCKER=true
    else
        echo_warn "Docker not found (optional for Qdrant)"
        HAS_DOCKER=false
    fi

    # 2. 创建目录
    echo_step "创建目录结构..."
    mkdir -p "${SKILL_ROOT}"/{src,hooks,scripts,tests,memory,knowledge}
    echo_success "目录创建完成: ${SKILL_ROOT}"

    # 3. 检查源文件
    echo_step "检查核心文件..."

    REQUIRED_FILES=(
        "src/config.py"
        "src/mem0_client.py"
        "src/transcript_parser.py"
        "src/memory_manager.py"
        "src/cli.py"
        "hooks/mem0_memory_hook.py"
    )

    MISSING_FILES=()
    for file in "${REQUIRED_FILES[@]}"; do
        if [ ! -f "${SKILL_ROOT}/${file}" ]; then
            MISSING_FILES+=("$file")
        fi
    done

    if [ ${#MISSING_FILES[@]} -gt 0 ]; then
        echo_warn "缺少以下文件，正在创建..."
        for file in "${MISSING_FILES[@]}"; do
            echo "  - $file"
            # 文件应该已由 Qoder 创建，这里仅提示
        done
    else
        echo_success "核心文件完整"
    fi

    # 4. 安装 Python 依赖
    echo_step "安装 Python 依赖..."

    # 检查 pip
    if ! $PYTHON_CMD -m pip --version &> /dev/null; then
        echo_warn "pip not found, trying pip3..."
        if ! command -v pip3 &> /dev/null; then
            echo_error "pip not found. Please install pip first."
            exit 1
        fi
    fi

    # 安装必要依赖
    $PYTHON_CMD -m pip install --user python-dotenv requests --quiet 2>/dev/null || true

    # 可选：安装 mem0
    echo -e "\n是否安装 mem0 (用于高级向量存储)? [Y/n]"
    read -r -t 10 response || response="y"
    response=${response:-y}

    if [[ "$response" =~ ^[Yy]$ ]]; then
        echo "安装 mem0..."
        $PYTHON_CMD -m pip install --user mem0 --quiet 2>/dev/null || echo_warn "mem0 安装失败，将使用降级模式"
    fi

    # 5. 启动 Qdrant (可选)
    if [ "$HAS_DOCKER" = true ]; then
        echo -e "\n是否启动 Qdrant 向量数据库? [Y/n]"
        read -r -t 10 response || response="y"
        response=${response:-y}

        if [[ "$response" =~ ^[Yy]$ ]]; then
            echo_step "启动 Qdrant..."

            # 检查是否已运行
            if docker ps | grep -q qdrant; then
                echo_success "Qdrant 已在运行"
            else
                docker run -d \
                    --name qdrant \
                    -p 6333:6333 \
                    -p 6334:6334 \
                    -v "${SKILL_ROOT}/memory/qdrant_storage:/qdrant/storage" \
                    qdrant/qdrant 2>/dev/null || echo_warn "Qdrant 启动失败"

                if curl -s http://localhost:6333/health &>/dev/null; then
                    echo_success "Qdrant 启动成功"
                else
                    echo_warn "Qdrant 可能未正常启动"
                fi
            fi
        fi
    else
        echo_warn "跳过 Qdrant 安装 (需要 Docker)"
    fi

    # 6. 配置环境变量
    echo_step "配置环境变量..."

    ENV_FILE="${SKILL_ROOT}/.env"

    if [ ! -f "$ENV_FILE" ]; then
        cat > "$ENV_FILE" << EOF
# Skill Memory Configuration
# Generated by install.sh

# Qdrant Configuration
SKILL_MEMORY_QDRANT_HOST=localhost
SKILL_MEMORY_QDRANT_PORT=6333
SKILL_MEMORY_QDRANT_COLLECTION=qoder_memory

# LLM/Embedding Provider
SKILL_MEMORY_LLM_PROVIDER=openai
SKILL_MEMORY_EMBEDDING_PROVIDER=openai
SKILL_MEMORY_LLM_MODEL=gpt-4o-mini
SKILL_MEMORY_EMBEDDING_MODEL=text-embedding-3-small

# API Key (optional, can also use environment variables)
# SKILL_MEMORY_API_KEY=your_key_here

# Search Parameters
SKILL_MEMORY_VECTOR_WEIGHT=0.7
SKILL_MEMORY_KEYWORD_WEIGHT=0.3
SKILL_MEMORY_DEFAULT_TOP_K=5
SKILL_MEMORY_PROMOTION_THRESHOLD=0.8
EOF
        echo_success "配置文件已创建: ${ENV_FILE}"
        echo_warn "请编辑 ${ENV_FILE} 填入您的 API Key"
    else
        echo_success "配置文件已存在: ${ENV_FILE}"
    fi

    # 7. 配置 Qoder Hooks
    echo_step "配置 Qoder Hooks..."

    QODER_CONFIG_DIR=$(dirname "$QODER_CONFIG")
    mkdir -p "$QODER_CONFIG_DIR"

    if [ -f "$QODER_CONFIG" ]; then
        # 备份原配置
        cp "$QODER_CONFIG" "${QODER_CONFIG}.backup.$(date +%Y%m%d%H%M%S)"
        echo_success "已备份原配置"

        # 添加 hooks 配置
        if grep -q '"hooks"' "$QODER_CONFIG"; then
            echo_warn "hooks 配置已存在，跳过"
        else
            # 使用 jq 添加 hooks (如果可用)
            if command -v jq &> /dev/null; then
                jq '.hooks.Stop = [{"hooks": [{"type": "command", "command": "'"${SKILL_ROOT}/hooks/mem0_memory_hook.py"'"}]}]' \
                    "$QODER_CONFIG" > "${QODER_CONFIG}.tmp" && \
                    mv "${QODER_CONFIG}.tmp" "$QODER_CONFIG"
                echo_success "Qoder Hooks 配置已添加"
            else
                echo_warn "jq 未安装，请在 ${QODER_CONFIG} 手动添加 hooks 配置"
            fi
        fi
    else
        # 创建新配置
        cat > "$QODER_CONFIG" << EOF
{
  "hooks": {
    "Stop": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "${SKILL_ROOT}/hooks/mem0_memory_hook.py"
          }
        ]
      }
    ]
  }
}
EOF
        echo_success "Qoder 配置已创建"
    fi

    # 8. 创建 CLI 软链接
    echo_step "创建 CLI 命令..."

    BIN_DIR="${HOME}/.local/bin"
    mkdir -p "$BIN_DIR"

    if [ -f "${SKILL_ROOT}/src/cli.py" ]; then
        ln -sf "${SKILL_ROOT}/src/cli.py" "${BIN_DIR}/memory"
        chmod +x "${BIN_DIR}/memory"

        if [ -d "$BIN_DIR" ] && [[ ":$PATH:" == *":$BIN_DIR:"* ]]; then
            echo_success "CLI 命令已安装: memory"
        else
            echo_warn "请将 ${BIN_DIR} 添加到 PATH"
            echo "  在 ~/.bashrc 或 ~/.zshrc 中添加:"
            echo "  export PATH=\"\$HOME/.local/bin:\$PATH\""
        fi
    fi

    # 9. 验证安装
    echo_step "验证安装..."

    if $PYTHON_CMD -c "from src.config import load_config; print('Config OK')" 2>/dev/null; then
        echo_success "Python 模块导入成功"
    else
        echo_warn "Python 模块导入失败，请检查 PYTHONPATH"
    fi

    if curl -s http://localhost:6333/health &>/dev/null; then
        echo_success "Qdrant 服务正常"
    else
        echo_warn "Qdrant 未运行，可选功能"
    fi

    # 完成
    echo -e "\n${GREEN}======================================${NC}"
    echo -e "${GREEN}  安装完成!${NC}"
    echo -e "${GREEN}======================================${NC}\n"

    echo "使用说明:"
    echo "  1. 编辑配置文件: ${ENV_FILE}"
    echo "  2. 添加 API Key"
    echo "  3. 使用 memory 命令:"
    echo "     memory add '用户偏好深色主题'"
    echo "     memory search '代码风格'"
    echo "     memory import --file <transcript.jsonl>"
    echo "     memory stats"
    echo -e "\n  ${BLUE}开始使用 AI 记忆系统吧!${NC}\n"
}

# 运行
main "$@"
